### ISSUE TITLE
Linux-level up

### ISSUE THREAD

**Issue by Morbius00** [1Spirit1/Learn-Linux#10]
<img src="https://img.shields.io/badge/hacktoberfest-2022-blueviolet" alt="Hacktober Badge"/>

## Linux- level UP
Undertaken as fullfillment of the action plan to complete a short Linux course focused on linux essentials, file- system, directory structure, the command-line and go through Linux privilege escalation on user and administrative accounts.

please assigned me for this.
regards,

**Comment by NamanManjkhola** [comment]
Sure @Morbius00 assigning this one to you.
You are good to go.

**Comment by 1Spirit1** [comment]
PR merged closing this issue
