### ISSUE TITLE
Basic Ubuntu Commandline Commands

### ISSUE THREAD

**Issue by daksh10110** [1Spirit1/Learn-Linux#12]
I can add a few basic Ubuntu Command line commands to this list. Please assign this to me.

**Comment by 1Spirit1** [comment]
Go for it @daksh10110

**Comment by daksh10110** [comment]
I have completed the work at https://github.com/1Spirit1/Learn-Linux/pull/14

Please check it out.

**Comment by 1Spirit1** [comment]
PR merged.
closing the issue
