### ISSUE TITLE
Create a content on Linux Mint

### ISSUE THREAD

**Issue by kodepirate** [1Spirit1/Learn-Linux#25]

**Comment by 1Spirit1** [comment]
Go for it @kodepirate

**Comment by kodepirate** [comment]
I have completed my work, but I am unable to create PR,
Help!

**Comment by kodepirate** [comment]
@1Spirit1 It will be great if you merge my PR

**Comment by 1Spirit1** [comment]
I was a bit busy past few days, or else I would've helped you. 
Happy to see that you resolved it on your own 🙂

**Comment by kodepirate** [comment]
@1Spirit1 No problem, its no big deal.😉✌️
