### ISSUE TITLE
Awesome Arch

### ISSUE THREAD

**Issue by Xester22** [1Spirit1/Learn-Linux#46]
# All about Arch (linux)
[Arch Linux] is an independently developed, x86-64 general purpose GNU/Linux distribution versatile enough to suit any role. Development focuses on simplicity, minimalism, and code elegance. Arch is installed as a minimal base system, configured by the user upon which their own ideal environment is assembled by installing only what is required or desired for their unique purposes.
> please assigne it to me

**Comment by 1Spirit1** [comment]
Sure, go on with it

**Comment by Xester22** [comment]
> Sure, go on with it

please add the hactober fest label
