### ISSUE TITLE
Installing VS Code in Ubuntu

### ISSUE THREAD

**Issue by harshxtanwar** [1Spirit1/Learn-Linux#5]
# Will write steps to install VS code in Ubuntu and also mention the cool themes and features of VS Code.

@1Spirit1 kindly accept this issue and label it as Hacktoberfest. I would love to work on it, bein a linux user myself, I think I can add many more things to the repository.

**Comment by 1Spirit1** [comment]
Sure @harshxtanwar go on!

**Comment by 1Spirit1** [comment]
PR merged. closing this issue
